"""
step5b_extract_from_pdf_sheet.py
=================================
Extracts handwritten character crops from SCANNED or PHOTOGRAPHED
versions of the character sheet generated by create_character_sheet.py.

Because we generated the sheet ourselves, we know the EXACT geometry —
no grid detection needed. Coordinates are computed directly from the
same constants used in create_character_sheet.py.

SHEET LAYOUT (from create_character_sheet.py):
  GRID_COLS   = 5        columns of character groups
  REF_SIZE    = 80 px    reference box (shaded, left of each group)
  WRITE_BOXES = 5        empty boxes the writer fills in
  BOX_SIZE    = 70 px    each writing box
  ROW_HEIGHT  = 130 px   full row height including label
  COL_WIDTH   = 485 px   REF_SIZE + 5*(BOX_SIZE+5) + 30
  PADDING     = 20 px    outer margin
  TITLE_H     = 60 px    title area at top

INPUT:
  - PDF or image file of a filled-in sheet
  - Scanned flat: use as-is
  - Photographed: deskew is applied automatically

OUTPUT:
  - PNG crops saved to output_dir/<class_name>/hw_<style>_<writer>_NNNN.png
  - Same format as synthetic data in dataset_raw/
  - Optional light augmentation (rotation + brightness)

USAGE:
  python step5b_extract_from_pdf_sheet.py

Edit the JOBS list at the bottom to point to your files.
"""

import os, sys, math
import numpy as np
import cv2
from pathlib import Path
from PIL import Image

# Try to import newa_classes from parent
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    from newa_classes import NEWA_CHARACTERS
    CHARS = list(NEWA_CHARACTERS.items())
except ImportError:
    print("⚠  newa_classes not found — add placeholder list")
    CHARS = [(f"char_{i:02d}", i) for i in range(82)]


# ═══════════════════════════════════════════════════════════════
# SHEET GEOMETRY — must match create_character_sheet.py exactly
# ═══════════════════════════════════════════════════════════════

GRID_COLS   = 5
WRITE_BOXES = 5
REF_SIZE    = 80
BOX_SIZE    = 70
ROW_HEIGHT  = 130
COL_WIDTH   = REF_SIZE + (WRITE_BOXES * (BOX_SIZE + 5)) + 30   # 485
PADDING     = 20
TITLE_H     = 60

# These are the ORIGINAL PIL pixel values from create_character_sheet.py.
# When a sheet is scanned or photographed, we apply a homography to warp
# it back to these canonical pixel coordinates before cropping.

CANONICAL_W = GRID_COLS * COL_WIDTH + 2 * PADDING   # 2465
# Height depends on how many characters are on the sheet

# Output settings
IMG_SIZE     = 128    # final crop size
# Blank detection: after resizing to 128x128, count pixels darker than INK_THRESH.
# Empty boxes have ~30 dark pixels (border + box number label bleed).
# Filled boxes have hundreds or thousands.
INK_THRESH   = 80    # pixel value below which we count as "ink"
BLANK_THRESH = 80    # fewer than this many ink pixels → treat cell as blank

# Augmentation
AUGMENT      = True
AUG_ROTATIONS  = [-5, -2, 2, 5]
AUG_BRIGHTNESS = [0.88, 1.12]

DEBUG_DIR = "debug_crops"


# ═══════════════════════════════════════════════════════════════
# LOAD & RASTERISE
# ═══════════════════════════════════════════════════════════════

def load_as_numpy(path: str, dpi: int = 150) -> np.ndarray:
    """
    Load a PDF or image file as an RGB numpy array.
    PDFs are rasterised at `dpi`; images are read directly.
    Returns HxWx3 uint8 array.
    """
    ext = Path(path).suffix.lower()
    if ext == ".pdf":
        try:
            import fitz   # PyMuPDF
        except ImportError:
            sys.exit("Install PyMuPDF:  pip install pymupdf --break-system-packages")
        doc  = fitz.open(path)
        page = doc[0]
        mat  = fitz.Matrix(dpi / 72, dpi / 72)
        pix  = page.get_pixmap(matrix=mat)
        arr  = np.frombuffer(pix.samples, dtype=np.uint8).reshape(
                   pix.height, pix.width, pix.n)
        if pix.n == 4:       # RGBA
            arr = arr[:, :, :3]
        doc.close()
        return arr
    else:
        img = cv2.imread(path)
        if img is None:
            sys.exit(f"Cannot read: {path}")
        return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)


# ═══════════════════════════════════════════════════════════════
# DESKEW / PERSPECTIVE CORRECTION
# ═══════════════════════════════════════════════════════════════

def _order_corners(pts):
    rect = np.zeros((4, 2), dtype=np.float32)
    s    = pts.sum(axis=1)
    d    = np.diff(pts, axis=1)
    rect[0] = pts[np.argmin(s)]   # top-left
    rect[2] = pts[np.argmax(s)]   # bottom-right
    rect[1] = pts[np.argmin(d)]   # top-right
    rect[3] = pts[np.argmax(d)]   # bottom-left
    return rect


def deskew(rgb: np.ndarray, n_chars_on_sheet: int) -> np.ndarray:
    """
    Attempt perspective correction. If no clear sheet boundary is found,
    returns the original image unchanged.
    The output is warped to the canonical pixel dimensions.
    """
    n_rows = math.ceil(n_chars_on_sheet / GRID_COLS)
    canonical_h = n_rows * ROW_HEIGHT + 2 * PADDING + TITLE_H

    gray    = cv2.cvtColor(rgb, cv2.COLOR_RGB2GRAY)
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    edges   = cv2.Canny(blurred, 40, 120)
    kernel  = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
    dilated = cv2.dilate(edges, kernel, iterations=3)

    contours, _ = cv2.findContours(dilated, cv2.RETR_EXTERNAL,
                                    cv2.CHAIN_APPROX_SIMPLE)
    img_area = rgb.shape[0] * rgb.shape[1]
    best_contour, best_area = None, 0
    for cnt in contours:
        area = cv2.contourArea(cnt)
        if area < img_area * 0.10:
            continue
        peri   = cv2.arcLength(cnt, True)
        approx = cv2.approxPolyDP(cnt, 0.02 * peri, True)
        if len(approx) == 4 and area > best_area:
            best_contour, best_area = approx, area

    if best_contour is None:
        print("  ⚠ No sheet boundary found — using full image as-is")
        return cv2.resize(rgb, (CANONICAL_W, canonical_h))

    pts  = best_contour.reshape(4, 2).astype(np.float32)
    rect = _order_corners(pts)
    dst  = np.array([[0, 0], [CANONICAL_W, 0],
                     [CANONICAL_W, canonical_h], [0, canonical_h]],
                    dtype=np.float32)
    M   = cv2.getPerspectiveTransform(rect, dst)
    out = cv2.warpPerspective(rgb, M, (CANONICAL_W, canonical_h))
    print("  ✓ Perspective correction applied")
    return out


# ═══════════════════════════════════════════════════════════════
# ALIGNMENT — compute cell boxes directly from sheet constants
# ═══════════════════════════════════════════════════════════════

def compute_cell_boxes(arr: np.ndarray, n_chars: int):
    """
    Computes (bx, by, bw, bh) for every writing cell.

    The canonical coordinates come straight from create_character_sheet.py.
    If the image was deskewed to canonical size, these coordinates are exact.
    Otherwise, they are scaled by the ratio between the image size and
    the canonical size.

    Returns: list of lists — cells[char_idx] = [(bx,by,bw,bh), ...]
    """
    h, w = arr.shape[:2]
    n_rows = math.ceil(n_chars / GRID_COLS)
    canonical_h = n_rows * ROW_HEIGHT + 2 * PADDING + TITLE_H

    sx = w / CANONICAL_W          # x scale factor
    sy = h / canonical_h          # y scale factor

    all_cells = []
    for i in range(n_chars):
        col = i % GRID_COLS
        row = i // GRID_COLS
        base_x = PADDING + col * COL_WIDTH
        base_y = PADDING + TITLE_H + row * ROW_HEIGHT

        char_cells = []
        for b in range(WRITE_BOXES):
            bx = base_x + REF_SIZE + 10 + b * (BOX_SIZE + 5)
            by = base_y + (REF_SIZE - BOX_SIZE) // 2  # = base_y + 5
            # Scale to actual image size
            bx_s = int(bx * sx)
            by_s = int(by * sy)
            bw_s = max(1, int(BOX_SIZE * sx))
            bh_s = max(1, int(BOX_SIZE * sy))
            char_cells.append((bx_s, by_s, bw_s, bh_s))
        all_cells.append(char_cells)

    return all_cells


# ═══════════════════════════════════════════════════════════════
# CROP UTILITIES
# ═══════════════════════════════════════════════════════════════

def crop_cell(arr, bx, by, bw, bh, pad=4) -> np.ndarray | None:
    """Crop one cell, convert to grayscale, normalise, and resize."""
    x0 = max(0, bx + pad)
    y0 = max(0, by + pad)
    x1 = min(arr.shape[1], bx + bw - pad)
    y1 = min(arr.shape[0], by + bh - pad)
    if x1 <= x0 or y1 <= y0:
        return None

    patch = arr[y0:y1, x0:x1]
    # Convert to grayscale
    if patch.ndim == 3:
        gray = cv2.cvtColor(patch, cv2.COLOR_RGB2GRAY)
    else:
        gray = patch.copy()

    # Normalise range
    gray = cv2.normalize(gray, None, 0, 255, cv2.NORM_MINMAX)

    # If dark background, invert (we want dark ink on white)
    if np.median(gray) < 128:
        gray = cv2.bitwise_not(gray)

    return cv2.resize(gray, (IMG_SIZE, IMG_SIZE), interpolation=cv2.INTER_AREA)


def is_blank(img: np.ndarray) -> bool:
    if img is None:
        return True
    return int((img < INK_THRESH).sum()) < BLANK_THRESH


# ═══════════════════════════════════════════════════════════════
# AUGMENTATION
# ═══════════════════════════════════════════════════════════════

def augment_crop(img: np.ndarray):
    """Yields (suffix, augmented_img) pairs."""
    h, w   = img.shape
    center = (w // 2, h // 2)
    for deg in AUG_ROTATIONS:
        M   = cv2.getRotationMatrix2D(center, deg, 1.0)
        rot = cv2.warpAffine(img, M, (w, h),
                             borderMode=cv2.BORDER_CONSTANT,
                             borderValue=255)
        yield f"r{deg:+d}", rot
    for fac in AUG_BRIGHTNESS:
        bright = np.clip(img.astype(float) * fac, 0, 255).astype(np.uint8)
        yield f"b{int(fac*100)}", bright


# ═══════════════════════════════════════════════════════════════
# SAVE
# ═══════════════════════════════════════════════════════════════

def count_existing(out_dir: str, class_name: str) -> int:
    d = os.path.join(out_dir, class_name)
    if not os.path.exists(d):
        return 0
    return len([f for f in os.listdir(d) if f.endswith(".png")])


def save_crop(img, out_dir, class_name, writer_id, style,
              suffix="", idx=0):
    class_dir = os.path.join(out_dir, class_name)
    os.makedirs(class_dir, exist_ok=True)
    existing = count_existing(out_dir, class_name)
    fname = f"hw_{style}_{writer_id}_{existing + idx:04d}"
    if suffix:
        fname += f"_{suffix}"
    fname += ".png"
    cv2.imwrite(os.path.join(class_dir, fname), img)


# ═══════════════════════════════════════════════════════════════
# DEBUG PREVIEW
# ═══════════════════════════════════════════════════════════════

def save_preview(arr, all_cells, chars, path, label="preview"):
    """Save a colour image with green overlays on write cells."""
    os.makedirs(DEBUG_DIR, exist_ok=True)
    vis = cv2.cvtColor(arr, cv2.COLOR_RGB2BGR) if arr.ndim == 3 else \
          cv2.cvtColor(arr, cv2.COLOR_GRAY2BGR)

    for i, (class_name, _) in enumerate(chars):
        if i >= len(all_cells):
            break
        for bx, by, bw, bh in all_cells[i]:
            cv2.rectangle(vis, (bx, by), (bx+bw, by+bh),
                          (0, 200, 60), 1)
            cv2.putText(vis, class_name[:5],
                        (bx+1, by+10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.22,
                        (200, 80, 0), 1)

    # Also draw ref boxes in blue
    h, w = arr.shape[:2]
    n_chars = len(chars)
    n_rows  = math.ceil(n_chars / GRID_COLS)
    canonical_h = n_rows * ROW_HEIGHT + 2 * PADDING + TITLE_H
    sx = w / CANONICAL_W
    sy = h / canonical_h
    for i in range(min(n_chars, len(all_cells))):
        col = i % GRID_COLS
        row = i // GRID_COLS
        rx = int((PADDING + col * COL_WIDTH) * sx)
        ry = int((PADDING + TITLE_H + row * ROW_HEIGHT) * sy)
        rw = int(REF_SIZE * sx)
        rh = int(REF_SIZE * sy)
        cv2.rectangle(vis, (rx, ry), (rx+rw, ry+rh),
                      (200, 100, 0), 1)

    stem  = Path(path).stem
    dpath = os.path.join(DEBUG_DIR, f"{stem}_{label}.jpg")
    max_w = 2000
    if vis.shape[1] > max_w:
        sc = max_w / vis.shape[1]
        vis = cv2.resize(vis, (max_w, int(vis.shape[0]*sc)))
    cv2.imwrite(dpath, vis)
    print(f"  Preview: {dpath}")
    print(f"  Green = write cells | Blue = reference box")
    return dpath


# ═══════════════════════════════════════════════════════════════
# MAIN PROCESSING FUNCTION
# ═══════════════════════════════════════════════════════════════

def process_sheet(
    path       : str,
    output_dir : str,
    writer_id  : str,
    style      : str  = "noto",
    do_deskew  : bool = True,
    augment    : bool = AUGMENT,
    preview_only: bool = False,
    chars      = None,
):
    """
    Extract handwriting samples from one filled-in character sheet.

    Args:
        path        : path to PDF or image (JPEG/PNG) of the filled sheet
        output_dir  : root output folder (e.g. 'dataset_raw/handwritten_noto')
        writer_id   : unique writer identifier string (e.g. 'writer1', 'suresh')
        style       : font style used in this sheet ('noto' or 'ranjana')
        do_deskew   : apply perspective correction for photos (True)
                      set False for flat-bed scans (already aligned)
        augment     : save light rotation/brightness augmentations
        preview_only: save a debug preview image without extracting crops
        chars       : character list override (default: NEWA_CHARACTERS)
    """
    if chars is None:
        chars = CHARS

    print(f"\n{'='*60}")
    print(f"Sheet: {path}")
    print(f"Writer: {writer_id}  Style: {style}  Mode: {'PREVIEW' if preview_only else 'EXTRACT'}")
    print(f"{'='*60}")

    arr = load_as_numpy(path)
    print(f"  Loaded: {arr.shape[1]}×{arr.shape[0]}px  ({arr.dtype})")

    # How many chars does this sheet actually have slots for?
    h, w = arr.shape[:2]
    n_rows_on_sheet = (h - 2*PADDING - TITLE_H) // ROW_HEIGHT
    slots_on_sheet  = n_rows_on_sheet * GRID_COLS
    n_chars = min(len(chars), slots_on_sheet)

    if n_chars < len(chars):
        print(f"  ⚠ Sheet has {slots_on_sheet} slots "
              f"({n_rows_on_sheet} rows × {GRID_COLS} cols) "
              f"but newa_classes has {len(chars)} chars.")
        print(f"  → Processing first {n_chars} characters only.")
        print(f"  → Reprint the sheet to capture all {len(chars)} characters.")

    chars_on_sheet = chars[:n_chars]

    # Deskew for photos; skip for flat scans
    if do_deskew:
        arr = deskew(arr, n_chars)
    else:
        # Just resize to canonical size for flat scans
        n_rows_c = math.ceil(n_chars / GRID_COLS)
        canonical_h = n_rows_c * ROW_HEIGHT + 2*PADDING + TITLE_H
        arr = cv2.resize(arr, (CANONICAL_W, canonical_h))

    # Compute cell coordinates
    all_cells = compute_cell_boxes(arr, n_chars)

    # Preview mode: just visualise, don't save crops
    if preview_only:
        save_preview(arr, all_cells, chars_on_sheet, path, "preview")
        print("  Preview saved. Open it to verify green boxes align with your writing.")
        print("  If misaligned, set do_deskew=True if you haven't already.")
        return 0

    # Extraction
    os.makedirs(output_dir, exist_ok=True)
    total_saved = total_blank = total_aug = 0
    debug_img   = cv2.cvtColor(arr, cv2.COLOR_RGB2BGR)

    for i, (class_name, _) in enumerate(chars_on_sheet):
        cells   = all_cells[i]
        box_idx = 0

        for bx, by, bw, bh in cells:
            crop = crop_cell(arr, bx, by, bw, bh)

            if crop is None:
                cv2.rectangle(debug_img, (bx,by), (bx+bw,by+bh),
                              (0,0,180), 1)
                continue

            if is_blank(crop):
                total_blank += 1
                cv2.rectangle(debug_img, (bx,by), (bx+bw,by+bh),
                              (0,200,200), 1)
                continue

            save_crop(crop, output_dir, class_name,
                      writer_id, style, idx=box_idx)
            box_idx     += 1
            total_saved += 1
            cv2.rectangle(debug_img, (bx,by), (bx+bw,by+bh),
                          (0,200,60), 1)
            cv2.putText(debug_img, class_name[:5],
                        (bx+1, by+10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.22,
                        (200,80,0), 1)

            if augment:
                for suffix, aug_img in augment_crop(crop):
                    save_crop(aug_img, output_dir, class_name,
                              writer_id, style, suffix,
                              idx=box_idx + total_aug)
                    total_aug += 1

    # Save debug image
    os.makedirs(DEBUG_DIR, exist_ok=True)
    stem  = Path(path).stem
    dpath = os.path.join(DEBUG_DIR, f"{stem}_debug.jpg")
    max_w = 2000
    if debug_img.shape[1] > max_w:
        sc = max_w / debug_img.shape[1]
        debug_img = cv2.resize(debug_img,
                               (max_w, int(debug_img.shape[0]*sc)))
    cv2.imwrite(dpath, debug_img)

    print(f"\n  ✓ Saved: {total_saved} | Augmented: {total_aug} | Blank: {total_blank}")
    print(f"  Debug: {dpath}")
    print(f"    GREEN  = saved correctly")
    print(f"    YELLOW = blank (writer left empty)")
    print(f"    RED    = bad region (out of bounds)")
    return total_saved


# ═══════════════════════════════════════════════════════════════
# SUMMARY
# ═══════════════════════════════════════════════════════════════

def print_summary():
    sources = {
        "Handwritten Noto"    : "dataset_raw/handwritten_noto",
        "Handwritten Ranjana" : "dataset_raw/handwritten_ranjana",
    }
    print("\n" + "="*60)
    print("DATASET SUMMARY")
    print("="*60)
    grand = 0
    for label, path in sources.items():
        if not os.path.exists(path):
            print(f"  {label:<26}: (not created yet)"); continue
        classes = [c for c in os.listdir(path)
                   if os.path.isdir(os.path.join(path, c))]
        if not classes:
            print(f"  {label:<26}: (empty)"); continue
        total = sum(
            len([f for f in os.listdir(os.path.join(path, c))
                 if f.endswith(".png")])
            for c in classes)
        avg   = total // len(classes) if classes else 0
        grand += total
        print(f"  {label:<26}: {total:5d} images "
              f"({len(classes)} classes, avg {avg}/class)")
    print(f"  {'TOTAL':<26}: {grand}")
    print("="*60)


# ═══════════════════════════════════════════════════════════════
# ▶  CONFIGURE YOUR JOBS HERE
# ═══════════════════════════════════════════════════════════════

if __name__ == "__main__":

    # ── STEP 1: Run with PREVIEW_ONLY=True first ─────────────────
    # Open debug_crops/<filename>_preview.jpg
    # Verify green boxes land on the writing cells
    # For flat PDF scans: do_deskew=False (coordinates are exact)
    # For phone photos: do_deskew=True

    PREVIEW_ONLY = False   # set True first → check preview → set False

    # ── PDF scans (from your printed+scanned sheets) ──────────────
    # These use do_deskew=False because the PDF geometry is exact
    process_sheet(
        path         = "handwritten_dataset/ww.jpg",
        output_dir   = "dataset_raw/handwritten_noto",
        writer_id    = "writer1",
        style        = "noto",
        do_deskew    = False,   # flat scan → no perspective correction needed
        augment      = True,
        preview_only = PREVIEW_ONLY,
    )

    # ── Phone photos of filled sheets ─────────────────────────────
    # These need perspective correction (do_deskew=True)
    # process_sheet(
    #     path         = "handwritten_dataset/ranjana_writer2_photo.jpg",
    #     output_dir   = "dataset_raw/handwritten_ranjana",
    #     writer_id    = "writer2",
    #     style        = "ranjana",
    #     do_deskew    = True,   # phone photo → apply perspective warp
    #     augment      = True,
    #     preview_only = PREVIEW_ONLY,
    # )

    # ── Add more writers by duplicating the block above ───────────

    print_summary()